{
  "Header": {
    "Original": "CVE-2020-36227 (A flaw was discovered in OpenLDAP before 2.4.57 leading to an infinite ...)",
    "Line": 168309,
    "ID": "CVE-2020-36227",
    "Description": "(A flaw was discovered in OpenLDAP before 2.4.57 leading to an infinite ...)"
  },
  "Annotations": [
    {
      "Original": "{DSA-4845-1 DLA-2544-1}",
      "Line": 168310,
      "Type": "xref",
      "Bugs": [
        "DSA-4845-1",
        "DLA-2544-1"
      ]
    },
    {
      "Original": "- openldap 2.4.57+dfsg-1",
      "Line": 168311,
      "Type": "package",
      "Package": "openldap",
      "Kind": "fixed",
      "Version": "2.4.57+dfsg-1"
    },
    {
      "Original": "NOTE: https://bugs.openldap.org/show_bug.cgi?id=9428",
      "Line": 168312,
      "Type": "NOTE",
      "Description": "https://bugs.openldap.org/show_bug.cgi?id=9428"
    },
    {
      "Original": "NOTE: https://git.openldap.org/openldap/openldap/-/commit/9d0e8485f3113505743baabf1167e01e4558ccf5 (OPENLDAP_REL_ENG_2_4_57)",
      "Line": 168313,
      "Type": "NOTE",
      "Description": "https://git.openldap.org/openldap/openldap/-/commit/9d0e8485f3113505743baabf1167e01e4558ccf5 (OPENLDAP_REL_ENG_2_4_57)"
    }
  ]
}