{
  "Header": {
    "Original": "CVE-2020-26137 (urllib3 before 1.25.9 allows CRLF injection if the attacker controls t ...)",
    "Line": 196645,
    "ID": "CVE-2020-26137",
    "Description": "(urllib3 before 1.25.9 allows CRLF injection if the attacker controls t ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2686-1}",
      "Line": 196646,
      "Type": "xref",
      "Bugs": [
        "DLA-2686-1"
      ]
    },
    {
      "Original": "- python-urllib3 1.25.9-1",
      "Line": 196647,
      "Type": "package",
      "Package": "python-urllib3",
      "Kind": "fixed",
      "Version": "1.25.9-1"
    },
    {
      "Original": "[buster] - python-urllib3 \u003cno-dsa\u003e (Minor issue)",
      "Line": 196648,
      "Type": "package",
      "Release": "buster",
      "Package": "python-urllib3",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://bugs.python.org/issue39603",
      "Line": 196649,
      "Type": "NOTE",
      "Description": "https://bugs.python.org/issue39603"
    },
    {
      "Original": "NOTE: https://github.com/urllib3/urllib3/commit/1dd69c5c5982fae7c87a620d487c2ebf7a6b436b (1.25.9)",
      "Line": 196650,
      "Type": "NOTE",
      "Description": "https://github.com/urllib3/urllib3/commit/1dd69c5c5982fae7c87a620d487c2ebf7a6b436b (1.25.9)"
    },
    {
      "Original": "NOTE: https://github.com/urllib3/urllib3/pull/1800",
      "Line": 196651,
      "Type": "NOTE",
      "Description": "https://github.com/urllib3/urllib3/pull/1800"
    }
  ]
}