{
  "Header": {
    "Original": "CVE-2018-10881 (A flaw was found in the Linux kernel's ext4 filesystem. A local user c ...)",
    "Line": 346066,
    "ID": "CVE-2018-10881",
    "Description": "(A flaw was found in the Linux kernel's ext4 filesystem. A local user c ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-1529-1 DLA-1423-1}",
      "Line": 346067,
      "Type": "xref",
      "Bugs": [
        "DLA-1529-1",
        "DLA-1423-1"
      ]
    },
    {
      "Original": "- linux 4.17.3-1",
      "Line": 346068,
      "Type": "package",
      "Package": "linux",
      "Kind": "fixed",
      "Version": "4.17.3-1"
    },
    {
      "Original": "[stretch] - linux 4.9.110-1",
      "Line": 346069,
      "Type": "package",
      "Release": "stretch",
      "Package": "linux",
      "Kind": "fixed",
      "Version": "4.9.110-1"
    },
    {
      "Original": "NOTE: https://bugzilla.kernel.org/show_bug.cgi?id=200015",
      "Line": 346070,
      "Type": "NOTE",
      "Description": "https://bugzilla.kernel.org/show_bug.cgi?id=200015"
    }
  ]
}