{
  "Header": {
    "Original": "CVE-2018-12896 (An issue was discovered in the Linux kernel through 4.17.3. An Integer ...)",
    "Line": 336236,
    "ID": "CVE-2018-12896",
    "Description": "(An issue was discovered in the Linux kernel through 4.17.3. An Integer ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-1731-1 DLA-1715-1}",
      "Line": 336237,
      "Type": "xref",
      "Bugs": [
        "DLA-1731-1",
        "DLA-1715-1"
      ]
    },
    {
      "Original": "- linux 4.18.20-1",
      "Line": 336238,
      "Type": "package",
      "Package": "linux",
      "Kind": "fixed",
      "Version": "4.18.20-1"
    },
    {
      "Original": "[stretch] - linux 4.9.144-1",
      "Line": 336239,
      "Type": "package",
      "Release": "stretch",
      "Package": "linux",
      "Kind": "fixed",
      "Version": "4.9.144-1"
    },
    {
      "Original": "NOTE: https://bugzilla.kernel.org/show_bug.cgi?id=200189",
      "Line": 336240,
      "Type": "NOTE",
      "Description": "https://bugzilla.kernel.org/show_bug.cgi?id=200189"
    },
    {
      "Original": "NOTE: https://github.com/lcytxw/bug_repro/tree/master/bug_200189",
      "Line": 336241,
      "Type": "NOTE",
      "Description": "https://github.com/lcytxw/bug_repro/tree/master/bug_200189"
    },
    {
      "Original": "NOTE: https://github.com/torvalds/linux/commit/78c9c4dfbf8c04883941445a195276bb4bb92c76",
      "Line": 336242,
      "Type": "NOTE",
      "Description": "https://github.com/torvalds/linux/commit/78c9c4dfbf8c04883941445a195276bb4bb92c76"
    }
  ]
}