{
  "Header": {
    "Original": "CVE-2021-39371 (An XML external entity (XXE) injection in PyWPS before 4.4.5 allows an ...)",
    "Line": 130668,
    "ID": "CVE-2021-39371",
    "Description": "(An XML external entity (XXE) injection in PyWPS before 4.4.5 allows an ...)"
  },
  "Annotations": [
    {
      "Original": "{DLA-2754-1}",
      "Line": 130669,
      "Type": "xref",
      "Bugs": [
        "DLA-2754-1"
      ]
    },
    {
      "Original": "- pywps 4.5.0-1",
      "Line": 130670,
      "Type": "package",
      "Package": "pywps",
      "Kind": "fixed",
      "Version": "4.5.0-1"
    },
    {
      "Original": "[bullseye] - pywps \u003cno-dsa\u003e (Minor issue)",
      "Line": 130671,
      "Type": "package",
      "Release": "bullseye",
      "Package": "pywps",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "[buster] - pywps \u003cno-dsa\u003e (Minor issue)",
      "Line": 130672,
      "Type": "package",
      "Release": "buster",
      "Package": "pywps",
      "Kind": "no-dsa",
      "Description": "Minor issue"
    },
    {
      "Original": "NOTE: https://github.com/geopython/OWSLib/issues/790",
      "Line": 130673,
      "Type": "NOTE",
      "Description": "https://github.com/geopython/OWSLib/issues/790"
    },
    {
      "Original": "NOTE: https://github.com/geopython/pywps/pull/616",
      "Line": 130674,
      "Type": "NOTE",
      "Description": "https://github.com/geopython/pywps/pull/616"
    }
  ]
}