{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "secalert@redhat.com",
      "ID": "CVE-2023-3159"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A use after free issue was discovered in driver/firewire in outbound_phy_packet_callback in the Linux Kernel. In this flaw a local attacker with special privilege may cause a use after free problem when queue_event() fails."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://github.com/torvalds/linux/commit/b7c81f80246fac44077166f3e07103affe6db8ff",
          "refsource": "MISC",
          "tags": [],
          "url": "https://github.com/torvalds/linux/commit/b7c81f80246fac44077166f3e07103affe6db8ff"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2023-06-12T21:15Z",
  "publishedDate": "2023-06-12T21:15Z"
}